"use client";

import { ThemeProvider } from "@/components/ThemeProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToggleTheme } from "@/components/ToggleTheme";
import { UserAvatar } from "@/components/ui/avatar/UserAvatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

import { usePathname } from "next/navigation";
import { SideMenu } from "@/components/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isSettingsPage = pathname === "/settings";
  const isSettingsPag = pathname === "/settings/account";

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="border-b">
            <div className="flex h-16 items-center px-4 container mx-auto">
              <Link href={"/finance"}>
                <div>PlanWise</div>
              </Link>
              <div className="ml-auto flex items-center space-x-4">
                <ToggleTheme />
                <UserAvatar />
              </div>
            </div>
          </div>
          <div className="flex container">
            {!isSettingsPage && !isSettingsPag ? <SideMenu /> : <></>}
            <div className="w-full pt-12">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
